apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: backend
  namespace: banking-ns
spec:
  hosts:
    - "azuremcdev.employee-mgmt.com"
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: gatewayserver
            port:
              number: 80
