apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-db-password-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql-db-password
    namespace: banking-ns

  data:
    - remoteRef:
        key: dbpassword
        property: dbpassword
      secretKey: password
