apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - awsmc.cncloudnet.com
  gateways:
    - istio-ingress/istio-gateway
  http:
    - route:
        - destination:
            host: banking-frontend-service
            port:
              number: 80
      match:
        - uri:
            prefix: /