releases:
  - name: redis
    chart: charts/redis
    values:
      - values/redis.yaml

  - name: configserver
    chart: charts/bank
    values:
      - values/configserver.yaml

  - name: eurekaserver
    chart: charts/bank
    values:
      - values/eurekaserver.yaml

  - name: gatewayserver
    chart: charts/bank
    values:
      - values/gatewayserver.yaml

  - name: accountsdb
    chart: charts/bank
    values:
      - values/accountsdb.yaml

  - name: cardsdb
    chart: charts/bank
    values:
      - values/cardsdb.yaml

  - name: loansdb
    chart: charts/bank
    values:
      - values/loansdb.yaml

  - name: accounts
    chart: charts/bank
    values:
      - values/accounts.yaml

  - name: cards
    chart: charts/bank
    values:
      - values/cards.yaml

  - name: loans
    chart: charts/bank
    values:
      - values/loans.yaml

  - name: message
    chart: charts/bank
    values:
      - values/message.yaml

  - name: kafka
    chart: charts/kafka
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - |
            cd charts/kafka || exit
            helm dependency build
            cd ..

  - name: kafka-ui
    chart: charts/bank
    values:
      - values/kafka-ui.yaml

  - name: prometheus
    chart: charts/kube-prometheus
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - |
            cd charts/kube-prometheus || exit
            helm dependency build
            cd ..

  - name: grafana-loki
    chart: charts/grafana-loki
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - |
            cd charts/grafana-loki || exit
            helm dependency build
            cd ..

  - name: grafana-tempo
    chart: charts/grafana-tempo
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - |
            cd charts/grafana-tempo || exit
            helm dependency build
            cd ..

  - name: grafana
    chart: charts/grafana
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - |
            cd charts/grafana || exit
            helm dependency build
            cd ..
