---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      imagePullSecrets:
        - name: aws-registry-key
      containers:
        - name: configserver
          image: 588738570846.dkr.ecr.us-east-1.amazonaws.com/banking-app:configserver-v3.3.5-79
          imagePullPolicy: Always
          ports:
            - containerPort: 8071

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  selector:
    app: configserver
  ports:
    - port: 8071
      targetPort: 8071
      protocol: TCP
  type: ClusterIP
