---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      imagePullSecrets:
        - name: azure-registry-key
      containers:
        - name: configserver
          image: aksemployeerepo.azurecr.io/banking-app:configserver-v3.3.5-118
          imagePullPolicy: Always
          ports:
            - containerPort: 8071
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
          resources:
            requests:
              memory: "100Mi"
              cpu: "128m"
            limits:
              memory: "120Mi"
              cpu: "256m"

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  selector:
    app: configserver
  ports:
    - port: 8071
      targetPort: 8071
      protocol: TCP
  type: ClusterIP
