---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
  labels:
    name: eurekaserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      imagePullSecrets:
        - name: azure-registry-key
      containers:
        - name: eurekaserver
          image: aksemployeerepo.azurecr.io/banking-app:eurekaserver-v3.3.5-118
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_APPLICATION_NAME
                  name: bank-cm
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: bank-cm
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: bank-cm
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
          resources:
            requests:
              memory: "100Mi"
              cpu: "128m"
            limits:
              memory: "120Mi"
              cpu: "256m"

---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    name: eurekaserver
spec:
  selector:
    app: eurekaserver
  ports:
    - port: 8070
      targetPort: 8070
      protocol: TCP
  type: ClusterIP
