---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
  labels:
    app: banking-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
        tier: frontend
    spec:
      imagePullSecrets:
        - name: azure-registry-key
      containers:
        - name: banking-frontend
          image: aksemployeerepo.azurecr.io/banking-app:frontend-v0.0.12-119
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 101

---
apiVersion: v1
kind: Service
metadata:
  name: banking-frontend-service
  labels:
    app: banking-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: banking-frontend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http


