---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    name: gatewayserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      imagePullSecrets:
        - name: azure-registry-key
      containers:
        - name: gatewayserver
          image: aksemployeerepo.azurecr.io/banking-app:gateway-v3.3.5-127
          imagePullPolicy: Always
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_APPLICATION_NAME
                  name: bank-cm
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: bank-cm
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: bank-cm
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                  name: bank-cm
          securityContext:
            runAsNonRoot: true
            runAsUser: 100

---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
  labels:
    name: gatewayserver
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  selector:
    app: gatewayserver
  ports:
    - port: 80
      targetPort: 8072
      protocol: TCP
  type: ClusterIP
