apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking-ns
resources:
  - mysql-externalName-service.yml
  - configmap.yml
  - configserver.yml
  - eurekaserver.yml
  - gatewayserver.yml
  - accounts.yml
  - cards.yml
  - loans.yml
  - frontend.yml
  - kafka.yml
  - kafka-cm.yml
  - kafka-network.yml
  - kafka-pvc.yml
  - kafka-stateful-set.yml
  - kafka-ui.yml
  - kafka-zookeeper-stateful-set.yml
  - message.yml
  - storage-class.yml
  - zool-log-pvc.yml
  - zool-pvc.yml