spring:
  application:
    name: "gatewayserver"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://awsbanking.cncloudnet.com"
              - "https://awsmcdev.cncloudnet.com"
              - "https://awsbanking.employee-mgmt.com"
              - "https://awsmcdev.employee-mgmt.com"
              - "http://localhost:5173"
              - "https://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "Gateways Application"
    version: "1.0.0"


logging:
  level:
    com:
      assignment:
        gateway: DEBUG
