---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb
  labels:
    app: accountsdb
spec:
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: accountsdb
          image: mysql:latest
          ports:
            - containerPort: 3306
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 3306
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: accountsdb
          volumeMounts:
            - name: mysql-accounts-db-vol
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-accounts-db-vol
          persistentVolumeClaim:
            claimName: accounts-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
  labels:
    name: accountsdb
spec:
  selector:
    app: accountsdb
  ports:
    - port: 3309
      targetPort: 3306
      protocol: TCP
