---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: fadhiljr/mssample:accounts-8.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: ACCOUNTS_APPLICATION_NAME
                  name: bank-cm
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: bank-cm
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: bank-cm
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: ACCOUNTS_DATASOURCE_URL
                  name: bank-cm
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
                  name: bank-cm
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                  name: bank-cm

---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    name: accounts
spec:
  selector:
    app: accounts
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
