---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: fadhiljr/mssample:configserver-8.0
          ports:
            - containerPort: 8071

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    name: configserver
spec:
  selector:
    app: configserver
  ports:
    - port: 8071
      targetPort: 8071
      protocol: TCP
  type: LoadBalancer
