---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-cm
data:
  EUREKA_APPLICATION_NAME: "eurekaserver"
  ACCOUNTS_APPLICATION_NAME: "accounts"
  ACCOUNTS_DATASOURCE_URL: "jdbc:mysql://accountsdb:3309/accountsdb"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
  LOANS_APPLICATION_NAME: "loans"
  LOANS_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
  CARDS_APPLICATION_NAME: "cards"
  CARDS_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
  GATEWAY_APPLICATION_NAME: "gatewayserver"
  GATEWAY_DATA_REDIS_CONNECT_TIMEOUT: "2s"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "1s"
  DYNAMIC_CONFIG_ENABLED: "true"
  KAFKA_CLUSTERS_0_NAME: "kafka_ms_test"
  KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_PROFILES_ACTIVE: "default"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"