---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    name: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: fadhiljr/mssample:gatewayserver-8.0
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_APPLICATION_NAME
                  name: bank-cm
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: bank-cm
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: bank-cm
            - name: SPRING_DATA_REDIS_CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_DATA_REDIS_CONNECT_TIMEOUT
                  name: bank-cm
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_REDIS_HOST
                  name: bank-cm
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_REDIS_PORT
                  name: bank-cm
            - name: SPRING_DATA_REDIS_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_REDIS_TIMEOUT
                  name: bank-cm
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                  name: bank-cm

---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
  labels:
    name: gatewayserver
spec:
  selector:
    app: gatewayserver
  ports:
    - port: 8072
      targetPort: 8072
      protocol: TCP
  type: LoadBalancer
