apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yml
  - configserver.yml
  - eurekaserver.yml
  - gatewayserver.yml
  - account-db-pv.yml
  - accounts-db-pvc.yml
  - accountsdb.yml
  - cards-db-pv.yml
  - cards-db-pvc.yml
  - cardsdb.yml
  - loans-db-pv.yml
  - loans-db-pvc.yml
  - loansdb.yml
  - configmap.yml
  - accounts.yml
  - cards.yml
  - loans.yml
  - message.yml
  - zool-pv.yml
  - zool-log-pvc.yml
  - zool-pv-log.yml
  - zool-log-pvc.yml
  - kafka-pv.yml
  - kafka-pvc.yml
  - kafka-cm.yml
  - kafka-stateful-set.yml
  - kafka-network.yml
  - kafka-zookeeper-stateful-set.yml
  - kafka-ui.yml