---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb
  labels:
    app: loansdb
spec:
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: loansdb
          image: mysql:latest
          ports:
            - containerPort: 3306
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 3306
          readinessProbe:
              initialDelaySeconds: 5
              periodSeconds: 5
              tcpSocket:
                port: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: loansdb
          volumeMounts:
            - name: mysql-loans-db-vol
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-loans-db-vol
          persistentVolumeClaim:
            claimName: loans-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
  labels:
    name: loansdb
spec:
  selector:
    app: loansdb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
