server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mc-dev.c3aema8a8skg.us-east-1.rds.amazonaws.com:3306/accountsdb
    username: admin
    password: 9GtEO9ILImLpCu8ORjG5
    #url: jdbc:mysql://localhost:3309/accountsdb
    #username: root
    #password: root
    #username: admin
    #password: pp57FYMKlrXTnj1DrXS5
    # new password: XWCZsLviuIASgOr9OZOw     user: admin
    # latest 9GtEO9ILImLpCu8ORjG5                admin
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      assignment:
        accounts: DEBUG






