services:
  client:
    image: fadhiljr/mssample:frontend-v4.0
    container_name: frontend
    ports:
      - "443:443"
  accountsdb:
    container_name: accountsdb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
      container_name: loansdb
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: loansdb
      extends:
        file: common-config.yml
        service: microservice-db-config

  cardsdb:
      container_name: cardsdb
      ports:
        - 3308:3306
      environment:
        MYSQL_DATABASE: cardsdb
      extends:
        file: common-config.yml
        service: microservice-db-config

  configserver:
    image: "fadhiljr/mssample:configserver-20.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8071"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "fadhiljr/mssample:eurekaserver-20.0"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8070" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    depends_on:
        configserver:
          condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "fadhiljr/mssample:accounts-20.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "fadhiljr/mssample:loans-20.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8090" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "fadhiljr/mssample:cards-20.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9000" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "fadhiljr/mssample:gatewayserver-21.0"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8072" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


networks:
  banks:
    driver: "bridge"