apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openpolicyagent
resources:
  - block-nodeport-service.yml
  - nodeport-constraint.yml
  - block-privileged-containers.yml
  - privileged-container-constraint.yml