apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-ns
  source:
    repoURL: https://github.com/dilafar/banking-microservice-app.git
    path: kustomization/overlays/dev
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true