{{- if .Values.volume_enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv_name }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.pv_host_path | quote }}
{{- end }}