{{- if .Values.volume_enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claim_name }}
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
{{- end }}