apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://keyvault-aks-db.vault.azure.net"
      serviceAccountRef:
        name: external-secrets-sa
        namespace: external-secrets