apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: istio-tls-external-secret
  namespace: istio-ingress
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore

  target:
    name: gateway-tls
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt }}"
        tls.key: "{{ .key }}"

  data:
    - remoteRef:
        key: secret/tls-key-istio-new
      secretKey: key
    - remoteRef:
        key: secret/tls-cert-istio-new
      secretKey: crt
