name: Cards Workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
    secrets:
      SONAR_PROJECT_KEY_CARDS:
        required: true
      SONAR_ORGANIZATION:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_URL:
        required: true

defaults:
  run:
    shell: bash

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Increment app version
        run: |
          cd cards
          echo "Incrementing app version..."
          mvn build-helper:parse-version versions:set \
              -DnewVersion=\"\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}\" \
              versions:commit
          version=$(grep -oPm1 '(?<=<version>)[^<]+' pom.xml)
          echo "IMAGE_VERSION=$version-${{ inputs.build_number }}" >> $GITHUB_ENV

      - name: Build and package
        run: |
          cd cards
          mvn clean package

      - name: Run Tests
        run: |
          cd cards
          mvn test

      - name: Checkstyle
        run: |
          cd cards
          mvn checkstyle:checkstyle

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          cd cards
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_CARDS }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/test-classes/com/assignment/accounts/

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: cards/.scannerwork/report-task.txt
          pollingTimeoutSec: 300
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}