name: Frontend Check Workflow
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      REGISTRY:
        required: true
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: banking-app
  EKS_CLUSTER: eks-terraform-2
  TARGET_URL: https://awsbanking.cncloudnet.com
defaults:
  run:
    shell: bash

jobs:
  frontend-web-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
            aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          sleep 60
          kubectl label namespace banking-ns istio-injection=enabled
          kubectl rollout restart deployment banking-frontend -n banking-ns
          sleep 180

      - name: Deployment Success Message
        run: |
          echo "✅ Successfully deployed at $(date)"

      - name: Run ZAP Scan
        run: |
            docker run -v $(pwd):/zap/wrk:rw -u 1000:1000 -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://awsbanking.cncloudnet.com -g gen.conf | tee reports/zap.conf || true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main || true
          git add .
          git commit -m "zap config changes updated by GitHub Actions"
          git push origin main