name: ConfigServer Workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      REGISTRY:
        required: true
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: banking-app
  EKS_CLUSTER: banking-eks
  CACHE_DIR: /home/runner/work/_temp/trivy
defaults:
  run:
    shell: bash

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Get public IP address
        run: |
          curl ifconfig.me

      - name: Increment app version
        run: |
          cd configserver
          echo "Incrementing app version..."
          mvn build-helper:parse-version versions:set \
              -DnewVersion=\"\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}\" \
              versions:commit
          version=$(grep -oPm1 '(?<=<version>)[^<]+' pom.xml)
          echo "IMAGE_VERSION=$version-${{ inputs.build_number }}" >> $GITHUB_ENV

      - name: Build and package
        run: |
          cd configserver
          mvn clean package
          mvn test

      - name: Start the configserver JAR
        run: |
          cd configserver
          java -jar target/*.jar &
        env:
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: check Trivy
        run: trivy --help

      - name: Cache Trivy Database
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: trivydb

      - name: Trivy Scan
        run: |
          bash trivy-docker-image-scan.sh configserver/Dockerfile ${{ env.CACHE_DIR }}

      - name: Build & Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.ECR_REPOSITORY }}
          region: ${{ env.AWS_REGION }}
          tags: configserver-v${{ env.IMAGE_VERSION }}
          daemon_off: false
          dockerfile: configserver/Dockerfile
          context: configserver

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

    #  - name: Trivy Scan Deployed Account Imange
    #    run: |
    #      bash trivy-k8s-scan.sh ${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }}:configserver-v${{ env.IMAGE_VERSION }} ${{ env.CACHE_DIR }}
