name: ConfigServer Workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      ACR_LOGIN_SERVER:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
env:
  ACR_REPOSITORY: banking-app
  CACHE_DIR: /home/runner/work/_temp/trivy
defaults:
  run:
    shell: bash

jobs:
  configserver-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'


      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Increment Backend App Version
        run: |
          cd configserver
          mvn build-helper:parse-version versions:set \
              -DnewVersion="${{ env.version }}-${{ inputs.build_number }}" \
              versions:commit
          version=$(grep -oPm1 '(?<=<version>)[^<]+' pom.xml)
          echo "IMAGE_VERSION=$version-${{ inputs.build_number }}" >> $GITHUB_ENV
          echo "Backend app version: $version"


      - name: Build and Package Backend
        run: |
          cd configserver
          mvn clean package
          mvn test


      - name: Start ConfigServer JAR
        run: |
          cd configserver
          java -jar target/*.jar &


      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy


      - name: Check Trivy
        run: trivy --help


      - name: Cache Trivy Database
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: trivydb


      - name: Trivy Docker Image Scan
        run: |
          bash trivy-docker-image-scan.sh configserver/Dockerfile ${{ env.CACHE_DIR }}


      - name: Run OPA Docker Scan
        run: |
          cd configserver
          docker run --rm -v $(pwd):/project openpolicyagent/conftest test --policy dockerfile-security.rego Dockerfile


      - name: Lint Dockerfile with Hadolint
        run: |
          cd configserver
          docker run --rm -i hadolint/hadolint < Dockerfile | tee hadolint_configserver.txt


      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Docker Image to ACR
        uses: docker/build-push-action@v5
        with:
          context: configserver
          file: configserver/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:configserver-v${{ env.IMAGE_VERSION }}


      - name: Scan Deployed Docker Image with Trivy
        run: |
          bash trivy-k8s-scan.sh ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:configserver-v${{ env.IMAGE_VERSION }} ${{ env.CACHE_DIR }} trivy-configserver.json


      - name: Run CIS Docker Benchmark
        run: |
          bash trivy-docker-bench.sh ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.ACR_REPOSITORY }}:configserver-v${{ env.IMAGE_VERSION }} trivy-bench-configserver.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin microservice-azure || true
          cp configserver/hadolint_configserver.txt reports/docker-lint/hadolint_configserver.txt
          git add .
          git commit -m "configserver microservice changes updated by GitHub Actions"
          git push origin microservice-azure
