name: Final Full Workflow

on:
  push:
    branches:
      - main

jobs:
  configserver:
    uses: ./.github/workflows/configserver.yml
    with:
      build_number: ${{ github.run_number }}

  eurekaserver:
    needs: configserver
    uses: ./.github/workflows/eurekaserver.yml
    with:
      build_number: ${{ github.run_number }}

  gatewayserver:
    needs: eurekaserver
    uses: ./.github/workflows/gateway.yml
    with:
      build_number: ${{ github.run_number }}

  cards:
    needs: gatewayserver
    uses: ./.github/workflows/cards.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_CARDS }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  loans:
    needs: gatewayserver
    uses: ./.github/workflows/loans.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_LOANS }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  accounts:
    needs: gatewayserver
    uses: ./.github/workflows/accounts.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  changeChart:
      runs-on: ubuntu-latest
      needs: accounts
      name: change version config
      steps:
        - run: echo ${{ needs.accounts.outputs.IMAGE_VERSION }}
       # - name: Checkout repository
       #   uses: actions/checkout@v3

       # - name: Set up environment
       #   run: echo "IMAGE_VERSION=${{ github.sha }}" >> $GITHUB_ENV

       # - name: Update chart versions
       #   run: |
       #       chmod +x chart-version-increment.sh