name: Final Workflow

on:
  push:
    branches:
      - main

jobs:
  configserver:
    uses: ./.github/workflows/configserver.yml
    with:
      build_number: ${{ github.run_number }}

  eurekaserver:
    needs: configserver
    uses: ./.github/workflows/eurekaserver.yml
    with:
      build_number: ${{ github.run_number }}