name: Final Full Workflow

on:
  workflow_dispatch:

jobs:
  configserver:
    uses: ./.github/workflows/configserver.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  eurekaserver:
    needs: configserver
    uses: ./.github/workflows/eurekaserver.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  gatewayserver:
    needs: eurekaserver
    uses: ./.github/workflows/gateway.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  cards:
    needs: gatewayserver
    uses: ./.github/workflows/cards.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_CARDS }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  loans:
    needs: gatewayserver
    uses: ./.github/workflows/loans.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_LOANS }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  accounts:
    needs: gatewayserver
    uses: ./.github/workflows/accounts.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  frontend:
    needs: gatewayserver
    uses: ./.github/workflows/frontend.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  changeChart:
      runs-on: ubuntu-latest
      needs: [accounts, frontend, cards,loans]
      name: change version config
      steps:
        - run: echo ${{ needs.accounts.outputs.IMAGE_VERSION }}

        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Pull Latest Changes
          run: |
            git pull origin main || true

        - name: Update chart versions
          run: |
              sed -i 's/^appVersion: .*/appVersion: accounts-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/accounts/values.yaml
              sed -i 's/^appVersion: .*/appVersion: cards-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/cards/values.yaml
              sed -i 's/^appVersion: .*/appVersion: configserver-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/configserver/values.yaml
              sed -i 's/^appVersion: .*/appVersion: eurekaserver-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/eurekaserver/values.yaml
              sed -i 's/^appVersion: .*/appVersion: gateway-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/gatewayserver/values.yaml
              sed -i 's/^appVersion: .*/appVersion: loans-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/loans/values.yaml
              sed -i 's/^appVersion: .*/appVersion: frontend-v'"${{ needs.frontend.outputs.VERSION }}"'/g' helm/charts/frontend/values.yaml
              chmod +x chart-version-increment.sh
              ./chart-version-increment.sh helm/Chart.yaml
              ./chart-version-increment.sh helm/charts/accounts/Chart.yaml
              ./chart-version-increment.sh helm/charts/configserver/Chart.yaml
              ./chart-version-increment.sh helm/charts/eurekaserver/Chart.yaml
              ./chart-version-increment.sh helm/charts/gatewayserver/Chart.yaml
              ./chart-version-increment.sh helm/charts/loans/Chart.yaml
              ./chart-version-increment.sh helm/charts/cards/Chart.yaml
              ./chart-version-increment.sh helm/charts/frontend/Chart.yaml
              cat helm/charts/cards/Chart.yaml
              cat helm/charts/loans/values.yaml
              cat helm/charts/frontend/Chart.yaml
              export REGISTRY=${{ secrets.REGISTRY }}
              export IMAGE_VERSION=${{ needs.accounts.outputs.IMAGE_VERSION }}
              export VERSION=${{ needs.frontend.outputs.VERSION }}
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:accounts-v${IMAGE_VERSION}|g" kustomization/base/accounts.yml
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:cards-v${IMAGE_VERSION}|g" kustomization/base/cards.yml 
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:configserver-v${IMAGE_VERSION}|g" kustomization/base/configserver.yml 
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:eurekaserver-v${IMAGE_VERSION}|g" kustomization/base/eurekaserver.yml 
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:gateway-v${IMAGE_VERSION}|g" kustomization/base/gatewayserver.yml 
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:loans-v${IMAGE_VERSION}|g" kustomization/base/loans.yml 
              sed -i "/containers:/,/^[^ ]/s|image:.*|image: ${REGISTRY}/banking-app:frontend-v${VERSION}|g" kustomization/base/frontend.yml 
              cat kustomization/base/accounts.yml

        - name: Configure Git
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

        - name: Commit and Push Changes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git add .
            git commit -m "Automated commit by GitHub Actions"
            git push origin main

 # eks-deployment:
 #   needs: changeChart
  #  uses: ./.github/workflows/eks_cluster_deploy.yml
 #   with:
 #     build_number: ${{ github.run_number }}
  #  secrets:
 #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #    REGISTRY: ${{ secrets.REGISTRY }}

  commit-changes:
    runs-on: ubuntu-latest
    needs: [ accounts, frontend, cards,loans, changeChart ]
    name: change gh-pages
    steps:
      - run: echo ${{ needs.accounts.outputs.IMAGE_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
            ref: gh-pages
            fetch-depth: 0

      - name: Download Chart Releaser
        run: |
            curl -LO https://github.com/helm/chart-releaser/releases/download/v1.7.0/chart-releaser_1.7.0_linux_amd64.tar.gz
            tar -xzf chart-releaser_1.7.0_linux_amd64.tar.gz
            sudo mv cr /usr/local/bin/

      - name:  Pull Latest Changes
        run: |
          git pull origin gh-pages || true
          ls -la
          sed -i 's/^appVersion: .*/appVersion: accounts-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/accounts/values.yaml
          sed -i 's/^appVersion: .*/appVersion: cards-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/cards/values.yaml
          sed -i 's/^appVersion: .*/appVersion: configserver-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/configserver/values.yaml
          sed -i 's/^appVersion: .*/appVersion: eurekaserver-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/eurekaserver/values.yaml
          sed -i 's/^appVersion: .*/appVersion: gateway-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/gatewayserver/values.yaml
          sed -i 's/^appVersion: .*/appVersion: loans-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/loans/values.yaml
          sed -i 's/^appVersion: .*/appVersion: frontend-v'"${{ needs.frontend.outputs.VERSION }}"'/g' helm/charts/frontend/values.yaml
          chmod +x chart-version-increment.sh
          ./chart-version-increment.sh helm/Chart.yaml
          ./chart-version-increment.sh helm/charts/accounts/Chart.yaml
          ./chart-version-increment.sh helm/charts/configserver/Chart.yaml
          ./chart-version-increment.sh helm/charts/eurekaserver/Chart.yaml
          ./chart-version-increment.sh helm/charts/gatewayserver/Chart.yaml
          ./chart-version-increment.sh helm/charts/loans/Chart.yaml
          ./chart-version-increment.sh helm/charts/cards/Chart.yaml
          ./chart-version-increment.sh helm/charts/frontend/Chart.yaml
           cat helm/charts/cards/Chart.yaml

      - name:  helm package
        env:
          CR_TOKEN: ${{ secrets.CR_TOKEN }}
        run: |
           cd helm
           cr package
           cr upload --owner dilafar --git-repo banking-microservice-app  --skip-existing
           cr index --owner dilafar --git-repo banking-microservice-app

      - name: Configure Git
        run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git add .
            git commit -m "Automated commit by GitHub Actions"
            git push origin gh-pages
