name: Final Full Workflow

on:
  push:
    branches:
      - main

jobs:
  configserver:
    uses: ./.github/workflows/configserver.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  eurekaserver:
    needs: configserver
    uses: ./.github/workflows/eurekaserver.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  gatewayserver:
    needs: eurekaserver
    uses: ./.github/workflows/gateway.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  cards:
    needs: gatewayserver
    uses: ./.github/workflows/cards.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_CARDS }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  loans:
    needs: gatewayserver
    uses: ./.github/workflows/loans.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY_LOANS }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  accounts:
    needs: gatewayserver
    uses: ./.github/workflows/accounts.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.REGISTRY }}

  changeChart:
      runs-on: ubuntu-latest
      needs: accounts
      name: change version config
      steps:
        - run: echo ${{ needs.accounts.outputs.IMAGE_VERSION }}
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Update chart versions
          run: |
              sed -i 's/^appVersion: .*/appVersion: accounts-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/accounts/values.yaml
              sed -i 's/^appVersion: .*/appVersion: cards-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/cards/values.yaml
              sed -i 's/^appVersion: .*/appVersion: configserver-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/configserver/values.yaml
              sed -i 's/^appVersion: .*/appVersion: eurekaserver-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/eurekaserver/values.yaml
              sed -i 's/^appVersion: .*/appVersion: gateway-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/gatewayserver/values.yaml
              sed -i 's/^appVersion: .*/appVersion: loans-v'"${{ needs.accounts.outputs.IMAGE_VERSION }}"'/g' helm/charts/loans/values.yaml
              chmod +x chart-version-increment.sh
              ./chart-version-increment.sh helm/Chart.yaml
              ./chart-version-increment.sh helm/charts/accounts/Chart.yaml
              ./chart-version-increment.sh helm/charts/configserver/Chart.yaml
              ./chart-version-increment.sh helm/charts/eurekaserver/Chart.yaml
              ./chart-version-increment.sh helm/charts/gatewayserver/Chart.yaml
              ./chart-version-increment.sh helm/charts/loans/Chart.yaml
              ./chart-version-increment.sh helm/charts/cards/Chart.yaml
              cat helm/charts/cards/Chart.yaml
              cat helm/charts/loans/values.yaml