name: Final Full Workflow

on:
  push:
    branches:
      - main

jobs:
  configserver:
    uses: ./.github/workflows/configserver.yml
    with:
      build_number: ${{ github.run_number }}

  eurekaserver:
    needs: configserver
    uses: ./.github/workflows/eurekaserver.yml
    with:
      build_number: ${{ github.run_number }}

  gatewayserver:
    needs: eurekaserver
    uses: ./.github/workflows/gateway.yml
    with:
      build_number: ${{ github.run_number }}

  cards:
    needs: gatewayserver
    uses: ./.github/workflows/cards.yml
    with:
      build_number: ${{ github.run_number }}

  loans:
    needs: gatewayserver
    uses: ./.github/workflows/loans.yml
    with:
      build_number: ${{ github.run_number }}

  accounts:
    needs: gatewayserver
    uses: ./.github/workflows/accounts.yml
    with:
      build_number: ${{ github.run_number }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: ${{ secrets.SONAR_URL }}