name: ConfigServer Workflow

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
env:
  CACHE_DIR: /home/runner/work/_temp/trivy
defaults:
  run:
    shell: bash

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: check Trivy
        run: trivy --help

      - name: Cache Trivy Database
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: trivydb

      - name: Trivy Scan
        run: |
          bash trivy-docker-image-scan.sh configserver/Dockerfile ${{ env.CACHE_DIR }}

      - name: OPA Docker Scan
        run: |
          cd configserver
          docker run --rm \
            -v $(pwd):/project \
            openpolicyagent/conftest test --policy dockerfile-security.rego Dockerfile

      - name: Docker Lint
        run: |
          cd configserver
          docker run --rm -i hadolint/hadolint < Dockerfile | tee hadolint_lint.txt